### ISSUE TITLE
Document purpose of examples

### ISSUE THREAD

**Issue by canadaduane** [mattjennings/svelte-typescript-component-template#2]
I'm not sure if I understand the purpose of the two examples in the `examples/` folder. Is it to show how to include the component in each case? What is unique to each case (`ts` vs `js`)? Perhaps this could go in the readme.

**Comment by mattjennings** [comment]
That's correct. I was using them to test to that it worked for svelte projects without a typescript preprocessor (examples/js) and that types still worked for typescript projects (examples/ts).

This is probably unnecessary to keep around for a template, though, so maybe I'll just get rid of the ts example and have only the js one as `/example`

**Comment by canadaduane** [comment]
Funny, I kept the ts one and removed the js :)

I think that would work fine though (keeping just the js).
