### ISSUE TITLE
Question about using your template

### ISSUE THREAD

**Issue by Takuma-The-Akai-Kage** [mattjennings/svelte-typescript-component-template#3]
Hi Matt,

I have made an package based on both the typescript (svelte) component-templates I found on GitHub. And I had it working after I saw your template. But after some changes to the package the dist folder stopt being published to NPM. Only the typescript files in the src folder are getting published. I was wondering if you could give the package a look and tell me what i am doing wrong:
https://github.com/open-anthro-projects/nekomata-ui/tree/main/packages/nekomata-ui

I hope you can help me with this. 

Kind regards,
Tom

**Comment by mattjennings** [comment]
I'm not sure what might be happening. I cloned your repo and ran `npm pack --dry-run` and these are the results

```bash
npm notice
npm notice 📦  nekomata-ui@0.0.20
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 508B   README.md
npm notice 118B   dist/index.js
npm notice 125B   dist/index.js.map
npm notice 3.4kB  dist/index.mjs
npm notice 60.7kB dist/index.mjs.map
npm notice 4.2kB  dist/index.umd.js
npm notice 60.7kB dist/index.umd.js.map
npm notice 63B    dist/ThemeStore/index.js
npm notice 135B   dist/ThemeStore/index.js.map
npm notice 1.4kB  dist/ThemeStore/ThemeStore.js
npm notice 1.3kB  dist/ThemeStore/ThemeStore.js.map
npm notice 44B    dist/ts/index.d.ts
npm notice 30B    dist/ts/ThemeStore/index.d.ts
npm notice 271B   dist/ts/ThemeStore/ThemeStore.d.ts
npm notice 1.2kB  package.json
npm notice 43B    src/index.ts
npm notice 30B    src/ThemeStore/index.ts
npm notice 1.3kB  src/ThemeStore/ThemeStore.ts
npm notice === Tarball Details ===
npm notice name:          nekomata-ui
npm notice version:       0.0.20
npm notice filename:      nekomata-ui-0.0.20.tgz
npm notice package size:  33.7 kB
npm notice unpacked size: 136.7 kB
npm notice shasum:        08c26e90a56c00dfb5faacfc5912c92b710eb107
npm notice integrity:     sha512-QWLkC0+H26zEQ[...]/Z5bkZtobr7hA==
npm notice total files:   19
npm notice
nekomata-ui-0.0.20.tgz
```

so that would suggest they are being included.

**Comment by Takuma-The-Akai-Kage** [comment]
Thanks for taking a look at it :) it only seems to fail with npm publish. Because when i run build a dist output is indeed made.

Again thank you for taking a look maybe it's in a program and not in the config.

Kind regards,
Tom

**Comment by mattjennings** [comment]
Hm hard to say. Perhaps you need to make a .npmignore file? 

I pretty much copied the [sveltejs/component-template](https://github.com/sveltejs/component-template) so I'm not sure if there's anything I've done that would affect an npm publish. If you discover there is though, let me know!

**Comment by Takuma-The-Akai-Kage** [comment]
To let you know my solution for now is to not use the prepublishOnly step in the package.json and to just run a build manually and publish that

Kind regards,
Takuma
