### ISSUE TITLE
preprocess.js errors on Windows because of paths

### ISSUE THREAD

**Issue by jf908** [mattjennings/svelte-typescript-component-template#4]
This line

https://github.com/mattjennings/svelte-typescript-component-template/blob/d1564edba9f30ef117d42b882a537999e08d5eed/scripts/preprocess.js#L68

errors on Windows (at least on my machine) because filePath uses / to separate paths whereas srcPath uses \

I worked around it by calling path.resolve on filePath to swap the slash around.

(Line 22)
```js
      await Promise.all(files.map((filePath) => preprocessSvelte(path.resolve(filePath))));
```

(Line 36)
```js

      files.map(async (filePath) => {
        filePath = path.resolve(filePath);
```

**Comment by mattjennings** [comment]
Would you be able to make a PR for this?

**Comment by jf908** [comment]
Sure thing

**Comment by mattjennings** [comment]
Awesome, thanks for fixing that!
